<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>android.widget.BtnDeleteCategory</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>android.widget.Button</value>
      <webElementGuid>08b66d79-b1b3-4c84-b903-25b83ffb6eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>586a3d1d-6eb1-4c59-b47a-6a8827e0cbe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DELETE</value>
      <webElementGuid>470d8f12-9f0f-4446-a6c6-7b80d10965ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>resource-id</name>
      <type>Main</type>
      <value>android:id/button1</value>
      <webElementGuid>f99097ba-cd8e-4404-84c5-fb3e21ba7e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>package</name>
      <type>Main</type>
      <value>com.avinashproduct.todo</value>
      <webElementGuid>0c835733-7c85-4dbf-89eb-20e1f63c73b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checkable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46bc0058-c460-4908-a921-49fd4e007a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba7c003b-4932-4f35-b6a8-dbe8ad2a0154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clickable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc5f6759-2f7d-4886-98f0-110690f18eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e073a173-be66-4542-8003-f8318ca15b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fdc45e4-f42b-44df-a255-8c18f8f9fabf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4973abd4-0c4e-448c-b741-407d805964a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrollable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ff6a641-63a1-44b1-8bbf-c3e5d7f3a829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>long-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>229ae8f5-70a2-4c2d-b4a1-68d1eafa0437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>password</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c40941b9-d3f5-490e-b316-14d6a8a3163d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a287267c-9fd7-4fcf-9019-e74f991ccd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>773</value>
      <webElementGuid>c072362e-8529-4202-bf15-d0e1ba9eac9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1209</value>
      <webElementGuid>9ba13872-b9b4-454e-9081-0b6060f06b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>191</value>
      <webElementGuid>8a646190-1c99-4609-9f06-17f023b06821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>116</value>
      <webElementGuid>77e96f15-db6d-45f6-a08d-c7f327e0e54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-focused</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>54ee5fac-3b46-4b80-abc4-6afc7eff749a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>a11y-important</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8b2146fd-4a1f-4aba-ae00-ee3176e11055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bounds</name>
      <type>Main</type>
      <value>[773,1209][964,1325]</value>
      <webElementGuid>e8ad2a78-db44-4fae-ba29-b898d29ec693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c558a48-55a5-4015-b535-be850c3c80ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>context-clickable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>638565f4-5323-4212-b613-de69ec30949b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dismissable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa51b547-b6c4-4ce6-b0a0-474286d0a8f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>displayed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76f183eb-b86b-457d-979a-ece3333f3549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>drawing-order</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6a888385-618d-4091-909a-266616f7e033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>heading</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e73e3b0-5e02-45eb-98b9-3e2c72692c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>live-region</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0600f802-e44a-4e5b-8cd8-bdcdfb7d1e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>screen-reader-focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>26e5c758-1038-45f2-8aa1-9568d76dad2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showing-hint</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c7aa517-fbba-46d0-a4f9-4c9a480da23b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text-entry-key</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1c39a983-6711-4fed-b63f-59cfeed0d9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.support.v7.widget.LinearLayoutCompat[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.Button[2]</value>
      <webElementGuid>8e5eba4c-e719-410e-ae23-e321c6f0c699</webElementGuid>
   </webElementProperties>
   <locator>//*[@class = 'android.widget.Button' and (@text = 'DELETE' or . = 'DELETE') and @resource-id = 'android:id/button1']</locator>
   <locatorCollection>
      <entry>
         <key>ACCESSIBILITY</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@class = 'android.widget.Button' and (@text = 'DELETE' or . = 'DELETE') and @resource-id = 'android:id/button1']</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>android:id/button1</value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>android.widget.Button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//hierarchy/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.support.v7.widget.LinearLayoutCompat[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.Button[2]</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector().className(&quot;android.widget.Button&quot;).text(&quot;DELETE&quot;).resourceId(&quot;android:id/button1&quot;).packageName(&quot;com.avinashproduct.todo&quot;).enabled(true).clickable(true).longClickable(false).checkable(false).checked(false).focusable(true).focused(false).scrollable(false).selected(false).index(1)</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
